### ISSUE TITLE
Hey guys, I'm unable to add you to dm

### ISSUE THREAD

**Issue by YunoGasai67** [daksh-gg/alternatives-to-carl-bot#2]
I'm trying to add you guys on discord but it says you're not accepting friend requests? I'm not too familiar with markdown and such so me making a pull request won't do much good..

**Comment by daksh-gg** [comment]
Hello there!
I have DMs open for some of the servers I am in, and friend requests on mutuals only. So that's why.
If you could drop your DIscord Name here, I'll be glad to add you back and discuss, or alternatively if you saw my profile. you can join my server and get in touch with me there. 

If all of that is too much. Feel free to send in your suggestion here.

**Comment by YunoGasai67** [comment]
Hey! I temp opened my friend requests so you can add me:

Sylveоn#0001

Gonna have to copy paste that because the o is Cyrillic so I can get the 0001 tag
